### ISSUE TITLE
black for jupyter notebooks

### ISSUE THREAD

**Issue by saurabhkankriya** [koaning/calmcode-feedback#11]
Hi,

We often use jupyter notebook and it makes sense to also use black in there to format our code. I am using the magic function `%%black`. Here are the steps to enable black in jupyter:

1.  Install the magic function: `pip install blackcellmagic`
2. Load the magic function into your jupyter notebook: `%load_ext blackcellmagic`
3. Use `%%black` magic function in the cells that you want to format

Maybe you can make a video describing the above steps.

Source: https://github.com/csurfer/blackcellmagic

**Comment by koaning** [comment]
I appreciate you approaching me with the idea, but I'm not sure about adding it. It's not a tool I would use and there's a few reasons for it; 

- Jupyter notebooks, in the end, are very much like notebooks. Not production code with unittests and code formatters. To me, the need for black occurs more in a package that you'd want to maintain for a long while as opposed to a notebook where you're exploring some data. 
- While I agree that notebooks should not be used as if they're junk food, I also don't think that the code in a jupyter notebook needs to uphold the same quality/standard as code in a python package. 
- There are many jupyter plugin tools out there and I'd like to keep the number of jupyter tools that I endorse on this website small. Odds are that users can get overwhelmed. 

I'll leave the issue open such that you get the opportunity to convince me otherwise. If not, I'll close it later.

**Comment by saurabhkankriya** [comment]
You are probably right. It makes sense to use black for long term use and when coding in collaboration. Plus too many tools for a user to use in jupyter notebook. 

Thanks for the feedback.
