### ISSUE TITLE
content suggestions

### ISSUE THREAD

**Issue by petrhrobar** [koaning/calmcode-feedback#160]
Hey Vincent,

I really enjoyed the content

I wanted to ask you/to recommend another piece of content. You are kind of covering deployment. Especially your tutorial on fastapi was super helpful.

As far as deployment go would you go a bit further? I think a ```Docker``` would be really nice thing to cover as well as some AWS things (```lambda```, ```sagemaker```).

I am also a huge fan of ```spacy``` would you cover that also a bit? I am frequently using their ```project feature``` even outside NLP projects

Cheers,

Petr

**Comment by koaning** [comment]
I work at [Explosion](https://explosion.ai/) now, so any spaCy-related educational material can be found on their [YouTube channel](https://www.youtube.com/c/ExplosionAI) and [blog](https://explosion.ai/blog). 

Docker is indeed on the to-do list. I'm a bit hesitant to cover any cloud-related tools, mainly because cloud providers are somewhat notorious when it comes to changing the API. That said, if you want to do lambda on AWS ... check out [chalice](https://github.com/aws/chalice). 

One delaying factor, I may become a father in a few months. So I may not be able to release new videos as regularly.

**Comment by koaning** [comment]
I've added these suggestions to our internal roadmap.
