### ISSUE TITLE
Add recommended books or references in notes

### ISSUE THREAD

**Issue by RaulPL** [koaning/calmcode-feedback#20]
First, thanks for the awesome content that you are creating. I love it.

I just watched the cvxpy videos and I think that adding some references or some follow-up books in the notes could be helpful for people that want to learn more about it.

Cheers.

**Comment by koaning** [comment]
The only books that I know on the topics ... are not *that* friendly to beginners. You really need to understand calculus and linear algebra pretty well. 

I suppose this resource might be the best that comes to mind: https://web.stanford.edu/~boyd/vmls/vmls.pdf. 

What is your opinion? I will say that that book is on a fascinating field (disclaimer, I have a masters degree in Operations Research).

**Comment by RaulPL** [comment]
You are right, it is not beginner friendly topic (I just started learning about it). I think the book you mentioned (vmls) might be a good starting point, it starts from the very basics and it mentions a lot of applications. Thanks for the recommendation. Other resources that I've found useful are these:

- [Convex Optimization Basics](https://youtu.be/oLowhs83aHk): it is a 21 min video that explains the basic concepts of convex optimization. The format is similar to one developed by 3Blue1Brown
- CVXPY [tutorial](https://www.cvxpy.org/tutorial/index.html) and [examples](https://www.cvxpy.org/examples/index.html)

**Comment by koaning** [comment]
+1 on that video, I'm watching it and it is quite enjoyable. I feel like it is still advanced though. There's terminology of empty sets, hessian matrices and something called positive semi-definite. I find it an enjoyable overview because I'm familiar with the material but I fear that it might indimidate others. 

Linking to the CVXPY tutorial and examples feels meaningful enough though and I see no hard in adding the book. 

If you're interested in learning more about the field of operations research (at least the practical bit) I may also recommend having a look at [or tools](https://developers.google.com/optimization/). It also has support for more integer based solvers as well as some logistical planning solutions (including many variants of travelling salesman).

**Comment by koaning** [comment]
Actually the video is really good, and so is that channel. I'll be adding a snippet of extra text to the second video. I'll let you know once it is up so you can review it.

**Comment by koaning** [comment]
Yep. Content is being merged right now. 

It deserves mentioning, I am thinking of making a series of videos on how to use cvxpy to create a custom machine learning model that is scikit-learn compatible. If you think there's some other content you'd love to see I'd be all ears.

**Comment by RaulPL** [comment]
> Actually the video is really good, and so is that channel

Yeah the videos in that channel are really good and concise. 

> If you're interested in learning more about the field of operations research (at least the practical bit) I may also recommend having a look at or tools

Thanks for the recommendation, I will take a look

> Content is being merged right now.

I just checked the new content and it looks good to me =)

> I am thinking of making a series of videos on how to use cvxpy to create a custom machine learning model that is scikit-learn compatible. If you think there's some other content you'd love to see I'd be all ears.

That's a great a idea since I don't know how to make a wrapper for scikit-learn.
I don't a have a suggestion  for content right now but if I get one I will let you know ;)

**Comment by koaning** [comment]
I'll consider this issues closed for now then.
