### ISSUE TITLE
method-chains course:  better readability by avoiding loop with range(len(data))

### ISSUE THREAD

**Issue by kdjavanc** [koaning/calmcode-feedback#209]
Dear calmcode creator,

I loved the course on method chains 👍. I should come to your site more often...
I was however surprised to see, in the 'Mutate' chapter, the typical Python anti-pattern: looping with range(len(data)).
Instead of:

```python
      for key, func in kwargs.items():
          for i in range(len(data)):
              data[i][key] = func(data[i])
```

more readable is:

```python
        for key, func in kwargs.items():
            for d in data:
                d[key] = func(d)
```

But I understand it's not worth changing this chapter only for this detail 😉
Cheers

**Comment by koaning** [comment]
There's a bunch in that implementation that I later changed actually 😅. 

Here's what is in `Clumper` at [the time of writing](https://github.com/koaning/clumper/blob/main/clumper/clump.py#L1227C1-L1233C38):

```python
        data = []
        for d in self.blob.copy():
            new = {k: v for k, v in d.items()}
            for key, func in kwargs.items():
                new[key] = func(new)
            data.append(new)
        return self._create_new(data)
```

It's been a few years, so I can't recall precisely what the real reason was, but I do like how making a new data list makes sure that we start with fresh state. However, making new lists all over the place like this is expensive and I've since opted for an implementation that does everything [on top of generators instead of lists](https://github.com/koaning/lazylines). 

Anyhow, while this comment is apprecaited (really!) I'll opt to not make a change to the course for now. There's a long todo list and re-recording this video isn't high up on the priority.
