### ISSUE TITLE
Not so much an issue

### ISSUE THREAD

**Issue by prteek** [koaning/calmcode-feedback#30]
I felt watching few videos was so much helpful for my work, I wished there was an upvote/like for topics.

**Comment by koaning** [comment]
Out of curiosity, what might make the website better if items were upvoted? Are you having trouble finding interesting content as is?

**Comment by prteek** [comment]
I wouldn't say trouble but as a beginner I was looking an easier way to find most helpful topics. The most viewed topics on stats page seemed a good entry point. Then I realised it's primarily because those topics appear at the top of website they have more visitors.
As for me particularly I liked some specific entries within a topic more than other entries within the same topic, so felt it would be a good way to highlight those by having an 'upvote' or 'most helpful' kind of design.

**Comment by koaning** [comment]
The issue with voting systems is that it is really hard to figure out what they represent. Something can be popular, but that does not mean that it is appropriate for beginners or good in terms of quality. Right now the most viewed content is the "args/kwargs" and "black". I don't think this is because of the quality of the content ... rather the fact that these are the first two collections on the front page. 

What instead may help more, and this is something I have been thinking about, is to have an extra page that allows you to explore topics. I eventually want to make content on "method chaining" but in order to get there it would really help that you've done "args/kwargs" as well as "lambda" beforehand. Part of the solution could be to make more specific groups ("tools for python people" is rather broad) but maybe also some sort of seperate page that demonstrates dependencies between topics. 

The dependency graph can get rather nasty tho. Here's a super small subset;

![image](https://user-images.githubusercontent.com/1019791/85270352-71b5be00-b479-11ea-8e90-0c98561587b4.png)

Just so I understand your situation better, what specific content are you currently interested in and what is tricky about the front page right now for you to find the content?

**Comment by prteek** [comment]
It’s true dependency graphs can get convoluted. Myself I am looking for some tips that make me be more productive as a programmer (since I am not one). That means taking stuff that I’d spend time on and automating those. Pytest was something I had only heard of and found very easy to follow and am using it now. So, was Black, it is something I did not even know existed. My background is in engineering and I am okay with Data Science part of things, something that helps improve my programs by automating, creating a framework is something I am trying to explore here.
Granted there are many topics that fall under this umbrella but I feel not all of them are relevant for what I do, that’s what popped the idea of having this great filter on the content for easier access.
I am beginning to realise though that the concise nature of content makes the whole point kid of moot too.
Because the content (for now) is not immense I can just go and watch as many topics and decide for myself which topics are most useful for me.
But, having a good index sort of like the one now python/data/case studies, does definitely help starters.

**Comment by koaning** [comment]
Suppose I'd make a page that offers collections of themes. From the top of my head, a page with something like this;

**Developer Flow**
*These tools make you a more productive developer. It's not so much about writing code, more about tools that allow you to write better packages.*
pytest, flake8, black, cookiecutter, makefile, pre-commit, virtualenv, readme files

**Python Standard Lib**
*These tools are from the python standard library and understanding them will make you more productive.*
pathlib, args/kwargs, decorators, comprehensions

**Python Util Packages**
*These packages are not part of python's core ecosystem but can be incredibly useful nonetheless.*
gin, tqdm, streamlit, fastapi locust

Would that help? I imagine that some tools might span across two categories, but at least this way there's some sort of an overview.

**Comment by koaning** [comment]
There's been a bit of radio silence, I'll close the issue for now but feel free to re-open by starting the conversation again.
