### ISSUE TITLE
More a discussion than an issue - QuantileTransformer Video

### ISSUE THREAD

**Issue by vtoliveira** [koaning/calmcode-feedback#32]
Hello koaning, thanks again for all great content you are making available to everyone.

I am not sure if this is appropriate or not, to make questions or start a debate, if not, please delete the issue.

In the Predict video for sklearn prep series, you discussed how QuantileTransformer can aid and help your models in defining better frontiers of classification. Illustrate by:

![image](https://user-images.githubusercontent.com/32197310/85859272-50afde80-b793-11ea-92e0-d8a4437597f7.png)

However, in your video about artificial stupidity, you brought an interesting point: algorithms such as classifiers build inference engine in regions where there is no data at all. Is not the same logic applied here when you make this transformation? You are changing the shape of your classifier decision boundary in way that it makes inference outside data scope, because I could have situation below:

![image](https://user-images.githubusercontent.com/32197310/85859734-02e7a600-b794-11ea-8b90-18ddf6b3969d.png)

(Imagine blue dots are purple ones, sorry about that...)

Does the question make sense?

**Comment by koaning** [comment]
Keep asking critical questions 👍 I like this one. 

If you were interested in training an outlier detection mechanism then using the `QuantileTransformer` might certainly be a bad idea. It will make it much harder to find outliers. The question is though, does a outlier detection system really need to use it? You could have a seperate pipeline for outlier detection and that's usually a good idea. Assuming that we've taken care of outliers with this pipeline ... are there then instances where a quantile transformation might make sense? 

I'd say: yes. If I look at the standard scaler model then, to me, the model learns an overly complicated shape. 

<img width="893" alt="image" src="https://user-images.githubusercontent.com/1019791/85887935-f0e42280-b7e8-11ea-8ed3-791a630a407d.png">

This odd shape might be a indicator that the model won't regularize very well. If this can be prevented with a quantile transformer, then this is a win. I wouldn't want to suggest that the quantile transformer is always a "must have" in machine learning pipeline but it certainly has moments where it can shine. 

It's also a lesser known transformer, which is why I added it.

[This document](https://scikit-learn.org/stable/auto_examples/preprocessing/plot_all_scaling.html#standardscaler) might help too, it shows the effect of different preprocessing methods.

**Comment by vtoliveira** [comment]
Right, I got the point now. You are focusing analysis on outliers effect, thus it makes total sense.
Thanks for your answer, I will keep asking if something comes up.

**Comment by koaning** [comment]
Keep asking good questions. Will close the issue for now.
