### ISSUE TITLE
Playback speed

### ISSUE THREAD

**Issue by koaning** [koaning/calmcode-feedback#37]
This is a way for me to measure if this is a feature folks *really* need. The upvotes can serve as a proxy.

**Comment by goretkin** [comment]
If the video were not embedded in an iframe, I'd be able to set it in the javascript console (or a bookmarklet) with

```js
var v = document.querySelector('video');
v.playbackRate = 1.5;
```

But this doesn't work:
![image](https://user-images.githubusercontent.com/581043/99454011-d0317c00-28f3-11eb-9b19-95c8187011ec.png)

related:
https://stackoverflow.com/q/60133095/415404

**Comment by paw-lu** [comment]
Just as an FYI to those that come across this, using [Video Speed Controller](https://chrome.google.com/webstore/detail/video-speed-controller/nffaoalbilbmmfgbnbgppjihopabppdk?hl=en) on Chrome allows for speeding up Vimeo videos.

Have been using it since the beginning to watch videos on calmcode quickly.

**Comment by ahmedhindi** [comment]
Awsome

**Comment by koaning** [comment]
@paw-lu that's a cool tip. I'll make a mental note to add this info to the FAQ.

**Comment by koaning** [comment]
Fixed!
