### ISSUE TITLE
License

### ISSUE THREAD

**Issue by koaning** [koaning/calmcode-feedback#61]
There's currently an automatically generated license, but maybe it's too "lawyer"-y and it doesn't 100% fit the angle that the website is trying to achieve. This issue was raised on [hackernews here](https://news.ycombinator.com/item?id=25123059#25127805). This is a place to allow for discussion around this topic.

**Comment by koaning** [comment]
One valid point from the hackernews forum;

> consider licensing the videos separately from the code in your videos. the creative commons family is a nice choice for artwork, but (stackoverflow has shown) perhaps not the best choice for code. for code that simply showcases features of a programming language, such as the "args / kwargs" video, that's not copyrightable because it's not a novel application, but it may come into play for the more advanced topics.

**Comment by andrewferguson** [comment]
(this is betamaxthetape from Hacker News, by the way)

Thanks for being so open to discussion on this. My main recommendation for you would be to consider what *you* want the license to achieve. It's never a good idea to pick a particular license because someone on the internet said you should!

Having said that, I would recommend you take a look at the Creative Commons license picker [1] that I recommended in my HN comment [2]. You don't have to use the license it recommends, but it allows you to think about some of the important questions involved such as commercial use and derivative works.

My own personal preference tends towards a copyleft-style license for the videos / content (e.g: the Creative Commons Share-Alike) and a more permissive license for the code itself (e.g: MIT), since this gives broad use of the code whilst ensuring that the videos / content remain openly available and attributed to you. But as I said above, the only person who can make this decision is you!

[1] https://creativecommons.org/choose/

[2] https://news.ycombinator.com/item?id=25128967

**Comment by koaning** [comment]
I'm nearly done with a redesign, which also gives an update to the license. I'll close the issue for now, but if there's any discussions to be had, feel free to post below. I've gone with @andrewferguson's advice here. 

![image](https://user-images.githubusercontent.com/1019791/111081876-ae44b080-8505-11eb-9577-b334baf3fcd7.png)
