### ISSUE TITLE
Issue with call timed_sleep call after applying decorator stopwatch in the video calmcode.io/decorators/decorate

### ISSUE THREAD

**Issue by yashwanthannem** [koaning/calmcode-feedback#66]
Issue with call timed_sleep call after applying decorator stopwatch in the video calmcode.io/decorators/decorate

**Comment by koaning** [comment]
Could you be more specific? Just mentioning "issue" isn't making it easy for me to figure out what might be going wrong.

**Comment by koaning** [comment]
That said ... after finding the link you're mentioning manually and checking the video again ... I think I understand. I think I see what is going wrong in that video. I'll need to reshoot the ending. I should be calling `sleep_random` instead of `timed_sleep`. 

Is this the issue that you're referring to?

**Comment by yashwanthannem** [comment]
Yes that is the issue.
Apologies for not being more specific .Will be sending detailed description if I find any issue in future

**Comment by koaning** [comment]
Just uploaded a new version.
