### ISSUE TITLE
Reasoning for deprecation to Old Content page

### ISSUE THREAD

**Issue by paw-lu** [koaning/calmcode-feedback#69]
Might be good to have a quick one sentence summary on why some content is deprecated to the `Old Content` page.

Along those lines, I'm curious as to why the csvkit content was deprecated? Better workflow or tool? Or issues with the original command? Appreciated!

---

Thanks for calmcode, it's one of my favorite educational websites! I really appreciate the thought and organization put into the material and how it's presented.

**Comment by koaning** [comment]
The reason for deprecation is likely different for each content block so it'd be hard to list it on the main page. I might add it as part of the appendix on the video page though -> that's certainly a valid idea. 

The reason for csvkit's deprecation is mainly because it's fairly slow and limited if you compare it to pandas. Instead of using csvkit it might just be better to write a simple python script that reads in a csv file and does the analysis you want. You might think "but I just want to explore the csv" but even for that use-case jupyter would be a better option. 

I wouldn't want a beginner to consider learning csvkit if they haven't checked pandas yet.
