### ISSUE TITLE
Gin VS Argparse VS Typer for configuration files

### ISSUE THREAD

**Issue by jroberayalas** [koaning/calmcode-feedback#73]
Not sure if this is a valid question, but if I have a script that uses global configuration settings that will be used throughout the code, is `gin` a good library to work with? I've seen references to [argspace](https://docs.python.org/3/library/argparse.html) and [Typer](https://typer.tiangolo.com/#an-example-with-two-subcommands), but I'm not sure if gin is the best way to go.

**Comment by koaning** [comment]
The question is certainly fair enough. I expect to make content on Typer this quarter. It's been on my todo list for a while. 

In my mind, I would go for typer if I have a collection of functions/library that I want to expose on the command line. You can combine a command line interface with a config file but there are moments where this might not make sense. 

For example, the calmcode website is built using a `python automator.py` command. This script has one user -> me. I don't need to worry about other people who might prefer a different configuration of the tool. That means that I can just resort to default values for the keyword arguments. If this were a tool that was public, where many people should be able to configure lots of settings, then the situation would be different. 

One thing to point out: it is up to *you* if you prefer to use gin or not. I think there's merit to the tool which is why I made content for it, but I wouldn't want to suggest that you must use the tool. You're totally free to ignore the tool if there's a nicer alternative for your situation.
